### ISSUE TITLE
Add DataTable component

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/catalyst#83]
## Component: DataTable
**What?** The DataTable will be used in the listing views in Products, Tags, Orders and more. 

**What's the current status in Admin?** Preliminary non-Catalyst version of this Table already exist on Tags (using Storefront Components) and Products (using Material UI).

## Design requirements

- [ ] Columns should be filterable
- [ ] Columns should be adjustable
- [ ] Table rows scroll indefinitely
- [ ] Pagination can be turned off
- [ ] Columns should be sortable (Alpha, Numeric)
- [ ] Hide/Show columns
- [ ] Edit action happens by click on row, not pencil icon
- [x] Zebra stripes #103

## Technical requirements

- [x] **Field/Input**: Have a filter field #103
- [x] **ActionMenu**: Have configurable bulk action dropdown #103
- [x] Allow passing in the header rows and data easily (without having to do JSX) #103
- [x] Allow overriding components for columns with JSX to change how the render #103
- [x] Support common column types like checkbox, number, left/right alighment, size #103
- [x] Have pagination controls #103
- [ ] Allow for adding more distinct filters (design TBD)

### Sub-components

- [x] ActionMenu: #103
- [ ] Filter data field: not done
- [x] MUI Checkbox #103
- [x] MUI Pagination: Input field, Dropdown, Pagination Buttons #103

## Responsive design requirements

- [ ]  Mobile: Size locks based on card size. Right side of table has no margin. Scroll left/right.

**Comment by machikoyasuda** [comment]
1. Data view and pagination first
2. Get the Filter View and Action Menu next.
3. Then do: Sorting columns
